[Assets] Assets creation transaction
Raptor3um/raptoreum pull request #250
Opened 2022-11-20 15:34 UTC by nandofw

- added new type of transaction: TRANSACTION_NEW_ASSET 
- implemented CNewAssetTx containing asset metadata
- added nAssetsForkBlock on chainparams
- added unit test that create a new assets

2022-11-21 15:33 UTC, npq7721 requested changes
unlike future transaction we want create new asset transactions to follow the same logic as registering protx where it get store in a merkle root proof in mined block. we can create another issue to add those if it is end up taking too big for this PR

2022-11-21 15:33 UTC, npq7721 commented on src/evo/providertx.h
> +    bool isunique = false;//true if this is asset is unique it has an identity per token (NFT flag)
should be isUnique

2022-11-21 15:33 UTC, npq7721 commented on src/evo/providertx.h
> +    uint8_t Decimalpoint = 0;
should be decimalPoint

2022-11-22 00:56 UTC, nandofw commented on src/evo/providertx.h
> +    uint8_t Decimalpoint = 0;
done

2022-11-22 01:00 UTC, nandofw commented
- added asset metadata validation

2022-11-24 13:45 UTC, npq7721 approved these changes
LGTM

2022-11-24 13:45 UTC, merged