assets_mint test fix
Raptor3um/raptoreum pull request #303
Opened 2023-07-11 03:36 UTC by CodeIsTheKey

The assets_mint test had a temporary workaround for a test failure under Windows.  The issue was that the TX index is written to disk asynchronously and in our particular test, we need to wait for it to be written before we can depend on it.

There were some major formatting problems with the file.  I reformatted the entire file with .clang-format

There are only two lines changed in this file if you ignore white space.

2023-07-11 03:36 UTC, CodeIsTheKey commented on src/test/assets_tests.cpp
> +#include <index/txindex.h>
Added this include (others were reordered based on .clang-format).

2023-07-11 03:37 UTC, CodeIsTheKey commented on src/test/assets_tests.cpp
> -    std::this_thread::sleep_for(std::chrono::milliseconds(50)); //txindex extra time for windows
Removed workaround

2023-07-11 03:38 UTC, CodeIsTheKey commented on src/test/assets_tests.cpp
> +    g_txindex->BlockUntilSyncedToCurrentChain();
This is what was missing.  Since we just created the transaction we need to reference, we need to wait for the index to be written before using it.

2023-07-11 13:57 UTC, nandofw requested changes

2023-07-11 13:57 UTC, nandofw commented on src/test/assets_tests.cpp
> +    {
```suggestion
    // Allow TX index to catch up with the block index.
    g_txindex->BlockUntilSyncedToCurrentChain();
    
    {
```
here need to wait for the index too

2023-07-11 13:57 UTC, nandofw commented on src/test/assets_tests.cpp
> +    {
```suggestion
    // Allow TX index to catch up with the block index.
    g_txindex->BlockUntilSyncedToCurrentChain();
    
    {
```
and here

2023-07-23 21:07 UTC, CodeIsTheKey commented on src/test/assets_tests.cpp
> +    {
Thanks - fixed.

2023-07-23 21:07 UTC, CodeIsTheKey commented on src/test/assets_tests.cpp
> +    {
Thanks - fixed.

2023-07-24 04:06 UTC, npq7721 approved these changes
LGTM

2023-07-24 14:34 UTC, nandofw approved these changes

2023-07-24 14:53 UTC, merged